### ISSUE TITLE
Unhandled exception in event loop

### ISSUE THREAD

**Issue by Mind0xP** [CaliDog/certstream-server-python#12]
Hi,
I'm trying to deploy the application on one of my servers, but for some reason, it does not work.
All requirements are installed with pip3.

<img width="1461" alt="screen shot 2018-01-21 at 4 25 49 pm" src="https://user-images.githubusercontent.com/10403988/35195159-0da21aa8-fec8-11e7-811a-1d57b358c3fd.png">

Thank you!

**Comment by Fitblip** [comment]
Hey @Mind0xP - I'm not sure what would be causing that. Can you give me some more information about your setup? OS/Cloud provider/etc?

**Comment by Fitblip** [comment]
Hey @Mind0xP - I figured out what was going on, this was just a fairly benign crash in the watcher coroutine for that particular CTL (as you can see, the SSL certificate for https://ct.akamai.com/ is actually invalid). 

I've blacklisted this particular CTL, so it shouldn't be an issue anymore. 

https://github.com/CaliDog/certstream-server/blob/33bff783d6e383e6d552d4a8ed23e7c1dcfd65ca/certstream/watcher.py#L17

Thanks for the bug report!
Ryan
