### ISSUE TITLE
Certificate Transparency Logs

### ISSUE THREAD

**Issue by patryk** [CaliDog/certstream-server-python#2]
`s/Certificate Transparency List/Certificate Transparency Log/g`
These were never called 'Lists'.

**Comment by Fitblip** [comment]
Hah! Oh man, you're totally right. Not sure where I got Certificate Transparency List from 😅 

That's absolutely my bad, and will be fixed shortly!

**Comment by Fitblip** [comment]
Hey @patryk - This should be fixed now, feel free to re-open/let me know if I missed any stragglers. 

Thanks again for pointing it out!

![](https://media0.giphy.com/media/JVdF14CQQH7gs/giphy.gif)
