### ISSUE TITLE
Documentation doesn't show it uses Python3

### ISSUE THREAD

**Issue by felixguerrero12** [CaliDog/certstream-server-python#6]
This implementation uses Python 3 since uvloop requires Python 3.5 or greater.

Commands to run to make it work:
apt install python3-pip
pip3 install --upgrade pip
pip3 install uvloop
pip3 install -r requirements.txt
python3 run_server.py

**Comment by Fitblip** [comment]
Ah yeah that's a good point! The server utilizes a bunch of python3 things (coroutines/asyncio, aiohttp, uvloop), but I should make that more clear in the docs! 

Thanks for the report! I'll update the readme to clarify.

![](https://media.giphy.com/media/xT8qBc8lTmMGtt7NrW/giphy.gif)

**Comment by Fitblip** [comment]
This is fixed with https://github.com/CaliDog/certstream-server/commit/3e0a6cbc947635d642246e17472f97d866abf16f

Please let me know if you'd change anything, otherwise have a great day!
