### ISSUE TITLE
Null CN with domains in `all_dns_names`

### ISSUE THREAD

**Issue by Fitblip** [CaliDog/certstream-server-python#7]
See https://twitter.com/deathy/status/927610920414728193 (and https://twitter.com/deathy/status/927616198774272000, https://twitter.com/deathy/status/927616495160561665, https://twitter.com/deathy/status/927616835180224514)

We've gotten a report that these certificates have null CN fields, but *also* have X509 SAN extension fields which are parsed fine, which AFAIK would be an invalid certificate (at least for a web browser). It's possible these are either just weird certificates that someone submitted to the logs, or this is a parsing bug somewhere in the subject/extension parser. 

It's worth grabbing these certificates and double checking to see if it's the former or the later.

**Comment by deathy** [comment]
Text list:
```
CN: [NONE] altName: DNS:computeron.ca, DNS:geeksquare.ca, DNS:primecomputers.ca certIndex: 168771964 certSource: {"url":"ct.googleapis.com/pilot","name":"Google 'Pilot' log"}
CN: [NONE] altName: DNS:flowers-to-the-world.com certIndex: 27859815 certSource: {"url":"mammoth.ct.comodo.com","name":"Comodo 'Mammoth' CT log"}
CN: [NONE] altName: DNS:flowers-to-the-world.com certIndex: 28266333 certSource: {"url":"sabre.ct.comodo.com","name":"Comodo 'Sabre' CT log"}
CN: [NONE] altName: DNS:computeron.ca, DNS:geeksquare.ca, DNS:primecomputers.ca certIndex: 163420098 certSource: {"url":"ct.googleapis.com/rocketeer","name":"Google 'Rocketeer' log"}
CN: [NONE] altName: DNS:asker.pk.klp.no, DNS:kontrast.pk.klp.no certIndex: 163480947 certSource: {"url":"ct.googleapis.com/rocketeer","name":"Google 'Rocketeer' log"}
```

> AFAIK would be an invalid certificate (at least for a web browser)

They actually seem to work fine in Chrome, computeron one:
![image](https://user-images.githubusercontent.com/43237/32510160-4ec9ba14-c3f8-11e7-902b-0067f4c3c3cd.png)
![image](https://user-images.githubusercontent.com/43237/32510193-5cff94dc-c3f8-11e7-8952-f832177b2079.png)

Not sure about other browsers and I assume some tools may have issues with no CN being present.

There's a new one "asker.pk.klp.no" in this list, works fine in browser, is actually Comodo EV Multi-Domain cert. Lots of info including company info in Subject, but no CN.

**Comment by Fitblip** [comment]
Huh, very interesting! Seems as though this is just a weird practice that works ¯\_(ツ)_/¯

I think this is probably good to close then. Thanks for doing a deep dive!
